name: Build and Test

on: push

jobs:
  build-with-cabal:
    name: ${{ matrix.os }} / ghc-${{ matrix.ghc }} / cabal-${{ matrix.cabal }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-10.15, windows-latest]
        ghc: [8.2.2, 8.4.4, 8.6.5, 8.8.4, 8.10.2]
        cabal: [3.2.0.0]
        exclude:
          # can't build zlib
          - os: windows-latest
            ghc: 8.10.2
            cabal: 3.2.0.0
    env:
      testcmd: cabal run -- darcs-test -f=123 -s=sn
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Configure git
      if: runner.os == 'Windows'
      run: git config --global core.autocrlf input

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Haskell
      id: setup-haskell-cabal
      uses: actions/setup-haskell@v1.1.3
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache cabal store
      uses: actions/cache@v2.1.3
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: cabal-store-${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-${{ hashFiles('**/*.cabal','**/cabal.project') }}
        restore-keys: |
          cabal-store-${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-
          cabal-store-${{ runner.os }}-${{ matrix.ghc }}-

    - name: Cache dist-newstyle
      uses: actions/cache@v2.1.3
      with:
        path: dist-newstyle
        key: dist-newstyle-${{ github.ref }}-${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-${{ hashFiles('darcs/*','src/**','harness/**','**/*.cabal','**/cabal.project') }}
        restore-keys: |
          dist-newstyle-${{ github.ref }}-${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}-
          dist-newstyle-${{ github.ref }}-${{ runner.os }}-${{ matrix.ghc }}-

    - name: Configure
      run: cabal configure --enable-tests -fwarn-as-error

    - name: Build dependencies
      run: cabal build --only-dependencies

    - name: Build
      run: cabal build

    - name: Haddock
      if: matrix.ghc != '8.2.2' && matrix.ghc != '8.4.4'
      run: cabal haddock lib:darcs

    - name: Run tests on Linux
      if: runner.os == 'Linux'
      run: ${{ env.testcmd }}

    - name: Run tests on MacOS
      if: runner.os == 'macOS'
      run: |
        brew install lighttpd
        brew install gnu-sed
        PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"
        ${{ env.testcmd }}

    - name: Run tests on Windows
      if: runner.os == 'Windows'
      # running the tests for all three patch formats takes over an hour
      run: cabal run -- darcs-test -f=2 -s=sn
